### ISSUE TITLE
deploying models post yaml is badly formed 

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [machinegurning/machinegurning.github.io#28]
![screenshot from 2017-03-20 20-42-26](https://cloud.githubusercontent.com/assets/4583655/24120827/d7828ca2-0dad-11e7-9b29-5658bf7a6269.png)

**Comment by ivyleavedtoadflax** [comment]
Fixed in the .md file in https://github.com/machinegurning/machinegurning.github.io/commit/9d586f67f2fd25fa9d85af3dd277727350f16017

**Comment by mammykins** [comment]
thanks buddy!
