### ISSUE TITLE
Error when running rmd2md()

### ISSUE THREAD

**Issue by mammykins** [machinegurning/machinegurning.github.io#4]
Following the excellent and comprehensive README compilation instructions, I installed the package and ran while in the correct working directory:

> getwd()
> [1] "C:/Users/mammykins/Documents/GitHub/machinegurning.github.io"
> 
> rmd2md::rmd2md()
> Error in value[[3L]](cond) : 
>   Error produced running rmd2md():Error in doTryCatch(return(expr), name, parentenv, handler): Figures directory: figures/ does not exist!

Which is strange, as the figures/ directory does appear to exist:

> list.dirs()[261]
> [1] "./figures"

**Comment by ivyleavedtoadflax** [comment]
Please can you post this on the issue tracker for the [rmd2md package](https://github.com/ivyleavedtoadflax/rmd2md/issues).

**Comment by ivyleavedtoadflax** [comment]
Please can you post this on the issue tracker for the [rmd2md package](https://github.com/ivyleavedtoadflax/rmd2md/issues).
